CREATE TABLE IF NOT EXISTS Items
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price        NUMERIC(10, 2),
    name         VARCHAR(255),
    description  VARCHAR(255),
    category     VARCHAR(255),
    pieces       INTEGER,
    heft         NUMERIC(10, 3),
    image        BYTEA,
    image_format VARCHAR(50)
);