CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price        NUMERIC(10, 2),
    name         VARCHAR(255),
    description  VARCHAR(255),
    category     VARCHAR(255),
    pieces       INTEGER,
    heft         NUMERIC(10, 3),
    image        VARCHAR(50)
);